<template>
  <v-container class="container">
  <div class="page">
  <div class="privacy">
    <h1>Privacy Policy</h1>
    <p>Effective date: July 21, 2020</p>
    <p>Preskilet ("us", "we", or "our") operates the https://preskilet.com website (here in after referred to as the "Service").</p>
    <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
    <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://preskilet.com/termsandconditions</p>
  </div>

  <div class="privacy">
    <h1>Definitions</h1>
     <ul>
      <li>Personal Data</li>
       <p>Personal Data means data about a living Individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
    </ul>
    <ul>
      <li>Usage Data</li>
       <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
    </ul>
    <ul>
      <li>Cookies</li>
       <p>Cookies are small files stored on your device (computer or mobile device).</p>
    </ul>
  </div>

  <div class="privacy">
    <h1>Information Collection and Use</h1>
    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
    <h3></h3>
    <p></p>
    <p></p>
  </div>

  <div class="privacy">
    <h1></h1>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
  </div>

  <div class="privacy">
    <h1></h1>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
  </div>

  <div class="privacy">
    <h1></h1>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
  </div>

  <div class="privacy">
    <h1></h1>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
  </div>

  <div class="privacy">
    <h1></h1>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
  </div>

  <div class ="privacy">
  <h1>Contact Us </h1>
  <p>If you have any questions about these Terms, please contact us.</P>
  <ul>
      <li>By email: contactus.preskilet@gmail.com</li>
    
    </ul>
  </div>  
</div>
</v-container>
</template>

<script>
export default {
  name: 'AppHeader'
};
</script>

<style>
.page{
  background-color:lightblue;
}
.container {
  padding: 60px 100px;
  
}
.privacy {
  max-width: 800px; 
  margin: 0 auto;
  padding: 20px;
  font-family: sans-serif; 
}

.privacy h1 {
  font-size: 24px;
  margin-bottom: 20px;
  padding :20px;
  text-align:center;
}

.privacy p {
  font-size: 16px;
  line-height: 1.5;
}
li{
  
}

</style>
